version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habitly-frontend
    working_dir: /app/
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: yarn serve
    ports:
      - 8080:8080
    networks:
    - habitly

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habitly-backend
    restart: unless-stopped
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /app/
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - habitly

  db:
    image: mysql:5.7
    container_name: habitly-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'habitly'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'habitly'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
    networks:
      - habitly

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      environment:
      - PMA_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      restart: unless-stopped
      ports:
      - 8081:80
      networks:
      - habitly

volumes:
  db:

networks:
  habitly:
    driver: bridge